baseURL = 'https://blog.chiendavid.com/'
defaultContentLanguage = 'zh-tw'
title = 'David'
theme = "PaperMod"
googleAnalytics = 'G-24NJ8FMP0K'
env = "production"


[params.homeInfoParams]
Title = "Hi! I am David 👋"
Content = "Nice to meet you!"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/f312213213"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/davidchien419/"

[[params.socialIcons]]
name = "Person"
url = "https://chiendavid.com"

[params]
ShowCodeCopyButtons = true
author = [ "David" ]
description = "我是簡毅，開始嘗試分享文章。"
ShowBreadCrumbs= true
comments= true

[sitemap]
changefreq = 'always'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[menu]
[[menu.main]]
identifier = 'Archive'
name = 'Archive'
url = '/archives/'
[[menu.main]]
identifier = 'Search'
name = 'Search'
url = '/search/'
[[menu.main]]
identifier = 'Tags'
name = 'Tags'
url = '/tags/'